spring.application.name=GestionHoteleria-Backend
server.port=${PORT:10000}

spring.profiles.active=postgres

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

app.jwt.secret=${JWT_SECRET:clave_super_segura_de_desarrollo_123456789}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
app.frontend-url=${FRONTEND_URL:http://localhost:5173}
app.upload-dir=${UPLOAD_DIR:uploads/habitaciones}
app.supabase.url=${SUPABASE_URL:}
app.supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY:}
app.supabase.storage.bucket=${SUPABASE_STORAGE_BUCKET:habitaciones}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method
