spring.application.name=GestionHoteleria-Backend

spring.profiles.active=${SPRING_PROFILES_ACTIVE:postgres}

spring.datasource.url=${DB_URL:jdbc:postgresql://TU_HOST_SUPABASE:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:TU_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

app.jwt.secret=${JWT_SECRET:clave_super_segura_de_desarrollo_123456789}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
app.frontend-url=${FRONTEND_URL:http://localhost:5173}